---
- hosts: all
  remote_user: root
  vars:
    epel_release_rpm_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    openshift_ansible_dir: "openshift-ansible/"
    openshift_playbook_path: "playbooks/byo/config.yml"
    openshift_version: "3.7"
  pre_tasks:
    - name: include_vars
      include_vars:
        file: "{{ item }}"
      with_items:
        - "{{ playbook_dir }}/../../../vars/all.yml"
        - "{{ playbook_dir }}/vars/{{ openshift_version }}.yml"

    - name: Include lib_utils
      import_role:
        name: lib_utils

    - name: set SELinux to permissive mode
      command: setenforce 0

    - name: set SELinux to permissive mode under configuration file
      selinux:
        policy: targeted
        state: permissive

    - name: stop and disable firewalld
      register: result
      service:
        state: stopped
        enabled: no
        name: firewalld
      failed_when: "result|failed and not 'Could not find the requested service' in result.msg"

    - name: install epel repository
      package:
        name: "{{ epel_release_rpm_url }}"
        state: present
      when:
        - ansible_distribution in ["CentOS","RedHat"]

    - name: Install openshift_facts requirements
      package:
        name: "{{ item }}"
      with_items:
        - python-yaml
        - python-ipaddress
        - wget
        - git
        - net-tools
        - bind-utils
        - iptables-services
        - bridge-utils
        - bash-completion
        - kexec-tools
        - sos
        - psacct
        - docker
        - NetworkManager

    - name: Include openshift_facts module
      import_role:
        name: "{{ openshift_ansible_dir }}/roles/openshift_facts"

    - name: Load openshift facts
      openshift_facts:
        role: common

    - name: Set facts for docker-storage-setup
      block:
        - name: Detect Operating System from ostree_booted
          stat:
            path: /run/ostree-booted
          register: ostree_booted
        - name: initialize_facts set fact openshift_is_atomic
          set_fact:
            openshift: "{{ openshift | combine({'common':{'is_atomic': ostree_booted.stat.exists}}, recursive=True) }}"
      when: "'is_atomic' not in openshift.common"

  roles:
    - "openshift-contrib/roles/docker-storage-setup"

  post_tasks:
    - name: Enable and start docker service
      service:
        state: started
        enabled: yes
        name: docker

    - name: Enable and start NetworkManager service
      service:
        state: started
        enabled: yes
        name: NetworkManager

- import_playbook: "{{ openshift_ansible_dir }}/playbooks/prerequisites.yml"
- import_playbook: "{{ openshift_ansible_dir | join_paths(openshift_playbook_path | default('playbooks/byo/config.yml')) }}"

- hosts: masters
  tasks:
    - name: Configure oc admin user for testing
      shell: |
        user_name="{{ admin_test_user_name | default('test_admin') }}"
        kubeconfig="/etc/origin/master/admin.kubeconfig"
        oc login -u system:admin --config=$kubeconfig
        oc get user "$user_name" --config=$kubeconfig || oc create user "$user_name" --config=$kubeconfig
        oc adm policy add-cluster-role-to-user cluster-admin "$user_name" --config=$kubeconfig
