---
- name: openshift cni config
  set_fact:
    cni_config: "{{ openshift_cni_config }}"
  when: platform=="openshift"

- name: kubernetes cni config
  set_fact:
    cni_config: "{{ kubernetes_cni_config }}"
  when: platform=="kubernetes"

- name: Render multus deployment yaml
  template:
    src: multus.yml
    dest: /tmp/multus.yml

- name: Delete multus Resources
  command: "{{ cluster_command }} delete -f /tmp/multus.yml --ignore-not-found"

- name: Render cni plugins deployment yaml
  template:
    src: cni-plugins.yml
    dest: /tmp/cni-plugins.yml

- name: Delete cni plugins Resources
  command: "{{ cluster_command }} delete -f /tmp/cni-plugins.yml --ignore-not-found"

# note: this rule does NOT delete /etc/pcidp/config.json file because k8s
# doesn't support finalizers to clean up mounted directory
- name: Uninstall SR-IOV device plugin
  block:
  - name: Render SR-IOV DP deployment yaml
    template:
      src: sriovdp.yml
      dest: /tmp/sriovdp.yml
  - name: Delete SR-IOV DP resources
    shell: "{{ cluster_command }} delete -f /tmp/sriovdp.yml --ignore-not-found"
  when: deploy_sriov_plugin

- name: Uninstall SR-IOV CNI plugin
  block:
  - name: Render SR-IOV CNI deployment yaml
    template:
      src: sriov-cni.yml
      dest: /tmp/sriov-cni.yml
  - name: Delete SR-IOV CNI resources
    shell: "{{ cluster_command }} delete -f /tmp/sriov-cni.yml --ignore-not-found"
  when: deploy_sriov_plugin

- name: Uninstall SR-IOV network
  block:
  - name: Render SR-IOV network CRD yaml
    template:
      src: sriov-crd.yml
      dest: /tmp/sriov-crd.yml
  - name: Delete SR-IOV network CRD
    shell: "{{ cluster_command }} delete -f /tmp/sriov-crd.yml --ignore-not-found"
    # ignore in case when crd is not known
    ignore_errors: yes
  when: deploy_sriov_plugin

- name: Render Kubernetes OVS plugin deployment yaml
  template:
    src: kubernetes-ovs-cni.yml
    dest: /tmp/ovs-cni.yml
  when: platform=="kubernetes"

- name: Render OpenShift OVS plugin deployment yaml
  template:
    src: openshift-ovs-cni.yml
    dest: /tmp/ovs-cni.yml
  when: platform=="openshift"

- name: Delete OVS plugin Resources
  command: "{{ cluster_command }} delete -f /tmp/ovs-cni.yml --ignore-not-found"

- name: Delete pre-0.3 OVS CNI plugin Resources
  command: "{{ cluster_command }} delete daemonset --namespace {{ network_namespace }} {{ legacy_ovs_provisioner_name }} --ignore-not-found"

- name: Delete pre-0.4 OVS CNI plugin Resources
  command: "{{ cluster_command }} delete daemonset --namespace {{ network_namespace }} {{ legacy_origin_node_provisioner_name }} --ignore-not-found"
  when: platform=="openshift"
