namespace: "kube-system"
docker_prefix: "kubevirt"
cluster: "openshift"
apb_action: "provision"
release_manifest_url: "https://github.com/kubevirt/kubevirt/releases/download"
kubevirt_template_dir: "{{ role_path }}/templates"
version: 0.6.0
offline_template_dir: "/opt/apb/kubevirt-templates"

default_vm_templates:
  - "vm-template-fedora"
  - "vm-template-windows2012r2"
  - "vm-template-rhel7"
kubevirt_privileged_policies:
  - kubevirt-privileged
  - kubevirt-controller
  - kubevirt-infra  # For KubeVirt v0.2.0
  - kubevirt-apiserver
