namespace: "kube-system"
docker_prefix: "kubevirt"
cluster: "openshift"
action: "provision"
release_manifest_url: "https://github.com/kubevirt/kubevirt/releases/download"
kubevirt_template_dir: "{{ role_path }}/templates"
version: v0.4.0
