---
- hosts: all
  remote_user: root
  vars_files:
    - "{{ playbook_dir }}/common/vars/default_vars.yml"
  pre_tasks:
    - name: Install python-yaml (required by openshift_facts)
      yum:
        name: python-yaml
    - name: Include openshift_facts module
      include_role:
        name: "{{ openshift_ansible_dir }}/roles/openshift_facts"
    - name: Load openshift facts
      openshift_facts:
        role: common
  roles:
    - "{{ playbook_dir }}/openshift/roles/prerequisites"
    - "openshift-contrib/roles/docker-storage-setup"
  post_tasks:
    - name: Enable and start docker service
      service:
        state: started
        enabled: yes
        name: docker

- include: "{{ openshift_ansible_dir }}/playbooks/deploy_cluster.yml"

- hosts: masters
  tasks:
    - name: Configure oc admin user for testing
      shell: |
        user_name="{{ admin_test_user_name | default('test_admin') }}"
        oc login -u system:admin
        oc get user "$user_name" || oc create user "$user_name"
        oc adm policy add-cluster-role-to-user cluster-admin "$user_name"
