- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Set prefix
      set_fact:
        prefix: "{{ prefix | default('.lago') }}"
    - name: Init Lago env
      command:
        lago init "{{ prefix }}" LagoInitFile.yml
      args:
        creates: "{{ prefix }}/default/uuid"
    - name: Remove user defined settigns from inventory
      blockinfile:
        path: "{{ inventory_file }}"
        marker: "# {mark} CUSTOM SETTINGS"
        state: absent
    - name: Create Ansible Hosts file from Lago env
      shell: lago --workdir "{{ prefix }}" ansible_hosts >> "{{ inventory_file }}"
    - name: Normalize inventory file
      replace:
        path: "{{ inventory_file }}"
        regexp: 'groups=(.*)'
        replace: '\1'
    - name: Refresh inventory
      meta: refresh_inventory
    - name: Start Lago env
      command: lago --workdir "{{ prefix }}" start


- hosts: all
  any_errors_fatal: True
  gather_facts: no
  tasks:
    - name: Wait for ssh
      wait_for:
        port: 22
        host: "{{ ansible_host }}"
        search_regex: OpenSSH
        delay: 10
      delegate_to: localhost
      connection: local
    - name: Mount docker_lib
      shell: |
        disk="/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_3"
        mount_path="/var/lib/docker"
        mkdir -p "$mount_path"
        mkfs.ext4 -F "$disk"
        echo -e "${disk}\t${mount_path}\text4\tdefaults\t0 0" >> /etc/fstab
        mount "$disk" "$mount_path"
    - name: Set docker storage disk path
      set_fact:
        docker_dev: "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_2"

- hosts: nfs
  any_errors_fatal: True
  tasks:
    - name: Mount nfs storage
      shell: |
        disk="/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_4"
        mount_path="/opt"
        mkdir -p "$mount_path"
        mkfs.ext4 -F "$disk"
        echo -e "${disk}\t${mount_path}\text4\tdefaults\t0 0" >> /etc/fstab
        mount "$disk" "$mount_path"

- hosts: lago-master:lago-node0
- hosts: all
  tasks:
    - debug:
        msg: "gather facts"

- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    # oc/kubectl requires that the master will be resolvable
    - name: Add master's fqdn to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars['lago-master']['ansible_default_ipv4']['address'] }} {{ hostvars['lago-master']['ansible_fqdn'] }}"

- hosts: lago-node0
  tasks:
    - name: Mark lago-node0 as infra
      set_fact:
        openshift_node_labels:
          region: infra
          zone: default
