---
- hosts: all
  remote_user: root
  pre_tasks:
    - name: override roles variables
      include_vars: "{{ item }}"
      with_items:
        - "{{ playbook_dir }}/kubernetes/vars/default_vars.yml"
        - "{{ playbook_dir }}/common/vars/default_vars.yml"
  tasks:
    - include_role:
        name: "{{ playbook_dir }}/kubernetes/roles/prerequisites"
      when: compile
    - include_role:
        name: "andrewrothstein.go-dev"
      when: compile
    - include_role:
        name: "{{ playbook_dir }}/common/roles/kubevirt"
      when: compile

- hosts: masters
  remote_user: root
  vars_files:
    - "{{ playbook_dir }}/kubernetes/vars/default_vars.yml"
  roles:
    - "{{ playbook_dir }}/kubernetes/roles/master"

- hosts: nodes
  remote_user: root
  vars_files:
    - "{{ playbook_dir }}/kubernetes/vars/default_vars.yml"
  roles:
    - "{{ playbook_dir }}/kubernetes/roles/node"

- hosts: masters
  remote_user: root
  pre_tasks:
    - name: override roles variables
      include_vars: "{{ item }}"
      with_items:
        - "{{ playbook_dir }}/common/vars/default_vars.yml"
  roles:
    - "{{ playbook_dir }}/kubernetes/roles/deploy-kubevirt"
