- hosts: all
  tasks:
    - debug:
        msg: "gather facts"

- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    kubevirt_repo_url: "https://github.com/kubevirt/kubevirt.git"
    kubevirt_repo_path: "{{ playbook_dir }}/kubevirt"
    kubevirt_mf_template: "{{ kubevirt_repo_path }}/manifests/release/kubevirt.yaml.in"
    kubevirt_mf: "{{ kubevirt_repo_path }}/manifests/release/kubevirt.yaml"
    docker_prefix: kubevirt
    docker_tag: "{{ kubevirt_release | default('latest') }}"
  tasks:
    - name: Clone Kubevirt's repo
      git:
        repo: "{{ kubevirt_repo_url }}"
        dest: "{{ kubevirt_repo_path }}"

    - name: Generate kubevirt.yaml from template
      template:
        src: "{{ kubevirt_mf_template }}"
        dest: "{{ kubevirt_mf }}"

# FIXME: we need to make sure that this play is executed only one single host
# Following line will do the job, but unfortunately it works in ansible >= 2.4
#- hosts: "{{ groups['masters'][0] }}"
- hosts: masters
  # unset http_proxy. required for running in the CI
  environment:
    http_proxy: ""
  vars:
    kubevirt_repo_path: "{{ playbook_dir }}/kubevirt"
    kubevirt_mf: "{{ kubevirt_repo_path }}/manifests/release/kubevirt.yaml"
    lib_oc_path: "{{ playbook_dir }}/openshift-ansible/roles/lib_openshift"
  pre_tasks:
    - name: Install Kubevirt
      debug:
        msg: "Installing Kubevirt"
  roles:
    - "{{ playbook_dir }}/openshift/roles/kubevirt"

  post_tasks:
    - name: List Kubevirt's reousrces
      shell: |
        oc project kube-system
        oc get pods
        oc get ds
