---
- src: https://github.com/openshift/openshift-ansible-contrib
  version: master
  name: openshift-contrib

- src: https://github.com/ansible/ansible-kubernetes-modules.git
  version: v0.3.1-5
  name: ansible.kubernetes-modules
