---
- name: Get Common Templates from {{ common_templates_manifest_url }}
  block:
  - name: Check for common-templates manifest in /tmp
    stat:
      path: "/tmp/common-templates.yaml"
    register: downloaded_templates

  - name: Download common-templates manifest
    get_url:
      url: "{{ common_templates_manifest_url }}/{{ release_tag }}/common-templates-{{ release_tag }}.yaml"
      dest: "/tmp/common-templates.yaml"
    when: downloaded_templates.stat.exists == false

- name: Create Kubevirt Templates
  shell: "{{ cluster_command }} apply -f /tmp/common-templates.yaml -n {{ kubevirt_ssp_namespace }}"