---
- name: Allow ceph OSD traffic
  iptables:
    action: insert
    chain: INPUT
    protocol: tcp
    destination_port: 6789
    jump: ACCEPT
  become: yes

- name: Allow ceph MDS traffic
  iptables:
    action: insert
    chain: INPUT
    protocol: tcp
    destination_port: 6800:7300
    jump: ACCEPT
  become: yes

- name: Save iptables configuration
  command: iptables-save
  become: yes
