cdi_namespace: "{{ cdi_image_namespace | default('golden-images') }}"
cdi_storageclass: "{{ cdi_kubevirt_storageclass | default('kubevirt') }}"
apb_action: "provision"
repo_tag: "{{ cdi_repo_tag | default('kubevirt') }}"
release_tag: "{{ cdi_release_tag | default('v1.1.1') }}"
controller_image: "{{ cdi_controller_image | default('cdi-controller') }}"
importer_image: "{{ cdi_importer_image | default('cdi-importer') }}"
cloner_image: "{{ cdi_cloner_image | default('cdi-cloner') }}"
