---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevirt-controller
  namespace: kube-system
  labels:
    kubevirt.io: ""
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-controller
  namespace: kube-system
  labels:
    kubevirt.io: ""
roleRef:
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kubevirt-controller
    namespace: kube-system
