---
- name: Login As Super User
  command: "oc login -u {{ admin_user }} -p {{ admin_password }}"
  when: cluster=="openshift"
        and admin_user is defined
        and admin_password is defined

- block:
  - name: Copy glusterfile provisioner YAML
    copy:
      src: glusterfile-provisioner.yml
      dest: /tmp/glusterfile-provisioner.yml

  - name: Determine the gluster namespace
    command: "oc get route --all-namespaces -l heketi={{ heketi_label }} -o jsonpath='{range .items[*]}{.metadata.namespace}'"
    register: namespace_cmd
    when: cluster == "openshift"

  - set_fact:
      gluster_namespace: "{{ namespace_cmd.stdout }}"
    when: namespace_cmd is defined

  - name: Deploy glusterfile provisioner pod
    command: "kubectl apply -n {{ gluster_namespace }} -f /tmp/glusterfile-provisioner.yml"
  when: external_provisioner

- name: Determine the heketi route
  command: "oc get route {{ heketi_route_name }} -n {{ gluster_namespace }} -o jsonpath='{.spec.host}'"
  register: route_cmd
  when: cluster == "openshift"

- set_fact:
    heketi_url: "{{ route_cmd.stdout }}"
  when: route_cmd is defined

- name: Get heketi admin key
  command: "oc get secret {{ heketi_secret_name }} -n {{ gluster_namespace }} -o jsonpath='{.data.key}'"
  register: key_cmd

- set_fact:
    heketi_admin_key: "{{ key_cmd.stdout }}"

- name: Render storage-glusterfs deployment yaml
  template:
    src: storage-glusterfs.yml.j2
    dest: /tmp/storage-glusterfs.yml

- name: Create storage-glusterfs Resources
  command: kubectl apply -f /tmp/storage-glusterfs.yml
