---
# TODO: wait for deprovision fo Web UI before removing the operator
- name: Deprovision Web UI and its operator
  block:
    - include_tasks: "deprovision.web-ui.yml"
    - include_tasks: "deprovision.operator.yml"
  when: apb_action == "deprovision"

- name: Provision Web UI via operator
  block:
    - include_tasks: "provision.operator.yml"
    - include_tasks: "provision.web-ui.yml"
  when: apb_action != "deprovision"

