---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: kubevirt
provisioner: kubernetes.io/glusterfs
reclaimPolicy: Delete
parameters:
  # Enable this when CNS supports cloning
  # smartclone: "true"
  resturl: "http://{{ heketi_route }}"
  restuser: admin
  secretName: "{{ heketi_secret_name }}"
  secretNamespace: "{{ heketi_namespace }}"
