---
- name: Login As Super User
  command: "oc login -u {{ admin_user }} -p {{ admin_password }}"
  when: cluster=="openshift"
        and admin_user is defined
        and admin_password is defined

- name: Check if {{ namespace }} exists
  shell: kubectl get ns | grep -w {{ namespace }} | awk '{ print $1 }'
  register: ns

- name: Create {{ namespace }} namespace
  shell: kubectl create namespace {{ namespace }}
  when: ns.stdout != namespace

- name: Add Privileged Policy
  command: "oc adm policy add-scc-to-user privileged -z {{ item }} -n {{ namespace }}"
  with_items:
    - kubevirt-privileged
    - kubevirt-controller
    - kubevirt-infra  # For KubeVirt v0.2.0
  when: cluster=="openshift"

- name: Add Hostmount-anyuid Policy
  command: "oc adm policy add-scc-to-user hostmount-anyuid -z kubevirt-infra -n {{ namespace }}"
  when: cluster=="openshift"

- name: Check for kubevirt.yml template in {{ kubevirt_template_dir }}
  stat:
    path: "{{ kubevirt_template_dir }}/kubevirt.yaml.j2"
  register: byo_template

- name: Download KubeVirt Template
  get_url:
    url: "https://raw.githubusercontent.com/kubevirt/kubevirt/v{{ version }}/manifests/release/kubevirt.yaml.in"
    dest: "{{ kubevirt_template_dir }}/kubevirt.yaml.in"
  when: byo_template.stat.exists == False

- name: Jinja2ify KubeVirt Go Manifest
  replace:
    path: "{{ kubevirt_template_dir }}/kubevirt.yaml.in"
    regexp: "{% raw %}{{\\.(\\w+)}}{% endraw %}"
    replace: "{% raw %}{{ \\1 }}{% endraw %}"
  when: byo_template.stat.exists == False

- name: Get List of Generated Manifests
  shell: awk '/GeneratedManifests/ {print $3}' "{{ kubevirt_template_dir }}/kubevirt.yaml.in" | sed -e 's/\"\|}//g'
  register: go_manifests
  when: byo_template.stat.exists == False

- name: Download Generated Manifests
  get_url:
    url: "https://raw.githubusercontent.com/kubevirt/kubevirt/v{{ version }}/manifests/generated/{{ item }}"
    dest: "{{ kubevirt_template_dir }}/{{ item }}.in"
  with_items:
  - "{{ go_manifests.stdout_lines }}"
  when: byo_template.stat.exists == False

- name: Remove GenearatedManifests References in KubeVirt Go Manifest
  lineinfile:
    path: "{{ kubevirt_template_dir }}/kubevirt.yaml.in"
    regexp: "{% raw %}{{index.*{% endraw %}"
    state: absent
  when: byo_template.stat.exists == False

- name: Assemble Complete jinaj2 Manifest template
  assemble:
    src: "{{ kubevirt_template_dir }}"
    dest: "{{ kubevirt_template_dir }}/kubevirt.yaml.j2"
    regexp: ".in$"
  when: byo_template.stat.exists == False

- name: Render Manifest Template
  template:
    src: "{{ kubevirt_template_dir }}/kubevirt.yaml.j2"
    dest: /tmp/kubevirt.yml

- fail:
- name: Create KubeVirt Resources
  command: kubectl apply -f /tmp/kubevirt.yml

- name: Check for vm templates in {{ kubevirt_template_dir }}
  stat:
    path: "{{ kubevirt_template_dir }}/{{ item }}.yaml"
  with_items:
    - "{{ default_vm_templates }}"
  register: byo_vm_templates

- name: Copy VM templates to /tmp
  copy:
    src: "{{ kubevirt_template_dir }}/{{ item }}.yaml"
    dest: "/tmp/{{ item }}.yaml"
  with_items: "{{ byo_vm_templates.results | selectattr('stat.exists') | map(attribute='item') | list }}"
  when: "{{ byo_vm_templates.results | selectattr('stat.exists') | map(attribute='item') | list | length > 0 }}"

- name: Download KubeVirt default VM templates
  get_url:
    url: "https://raw.githubusercontent.com/kubevirt/kubevirt/v{{ version }}/cluster/{{ item }}.yaml"
    dest: "/tmp/{{ item }}.yaml"
  with_items:
    - "{{ default_vm_templates }}"
  when: cluster == "openshift" and "{{ byo_vm_templates.results | selectattr('stat.exists') | map(attribute='item') | list | length == 0 }}"

- name: Create default VM templates in OpenShift Namespace
  shell: "oc apply -f /tmp/{{ item }}.yaml -n openshift"
  with_items:
    - "{{ default_vm_templates }}"
  when: cluster == "openshift"
