---
- name: Delete Service Account
  command: kubectl delete serviceaccount {{service_account}} -n {{namespace}}
  when: sa.stdout == ""

- name: Revoke anyuid access to {{service_account}} SA if using OCP
  command: oc adm policy remove-scc-to-user anyuid -z {{service_account}} -n {{namespace}}
  when: cluster == "openshift"

- name: Delete {{privileged_service_account}} serviceaccount
  command: kubectl create serviceaccount {{privileged_service_account}} -n {{ namespace }}
  when: psa.stdout == ""

- name: Revoke privileged access to {{privileged_service_account}} serviceaccount
  command: oc adm policy remove-scc-to-user privileged system:serviceaccount:{{ namespace }}:{{privileged_service_account}}
  when: cluster=="openshift"

- name: Select a host for Mariadb hostpath
  command: kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="Hostname")].address}'
  register: node_hostname

- name: Label node to host Mariadb
  command: kubectl label node "{{ node_hostname.stdout }}" "{{infra_node_label}}"-

- name: Include  Rabbitmq
  include_role:
    name: ansible-role-k8s-rabbitmq
  vars:
    action: deprovision

- name: Include Cinder
  include_role:
    name: ansible-role-k8s-cinder
  vars:
    action: deprovision

