---
- name: Delete Service Account
  command: kubectl delete serviceaccount {{service_account}} -n {{namespace}}
  when: sa.stdout == ""

- name: Delete {{privileged_service_account}} serviceaccount
  command: kubectl create serviceaccount {{privileged_service_account}} -n {{ namespace }}
  when: psa.stdout == ""

- name: Select a host for MariaDB hostpath
  command: kubectl get nodes --selector="{{infra_node_label}}"=true
  register: infra_node_hostnames

- name: Remove label on the nodes that host MariaDB
  command: kubectl label node "{{ item }}" "{{infra_node_label}}"-
  with_items: "{{ infra_node_hostnames.stdout.split() }}"

- name: Include  RabbitMQ
  include_role:
    name: ansible-role-k8s-rabbitmq
  vars:
    action: deprovision

- name: Include Cinder
  include_role:
    name: ansible-role-k8s-cinder
  vars:
    action: deprovision

- name: Render MariaDB
  template:
    src: "{{ storage_cinder_template_dir }}/mariadb.yml.j2"
    dest: /tmp/storage-cinder-mariadb.yml

- name: Delete storage-cinder-mariadb Resources
  command: kubectl delete -f /tmp/storage-cinder-mariadb.yml --ignore-not-found

