---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubevirt-web-ui-operator
  namespace: kube-public
subjects:
- kind: ServiceAccount
  name: kubevirt-web-ui-operator
  namespace: {{ kubevirt_web_ui_namespace }}
roleRef:
  kind: Role
  name: kubevirt-web-ui-operator
  apiGroup: rbac.authorization.k8s.io
