openshift_image_tag: v3.9.0
openshift_service_catalog_image_version: "{{ openshift_image_tag }}"
container_images:
  - "openshift/origin:{{ openshift_image_tag }}"
  - "openshift/node:{{ openshift_image_tag }}"
  - "openshift/openvswitch:{{ openshift_image_tag }}"
  - "openshift/origin-service-catalog:{{ openshift_image_tag }}"
  - "openshift/origin-web-console:{{ openshift_image_tag }}"
  - "ansibleplaybookbundle/origin-ansible-service-broker:latest"
  - "quay.io/coreos/etcd:latest"
  - "registry.fedoraproject.org/latest/etcd"
