---
- name: install cockpit packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - cockpit
    - cockpit-kubernetes

- name: enable and start cockpit service
  service:
    name: "cockpit.socket"
    state: started
    enabled: yes

- name: copy kubernetes deployment script
  template:
    src: deploy_kubernetes.j2
    dest: /root/deploy_kubernetes.sh
    mode: 0755

- name: deploy kubernetes
  shell: /root/deploy_kubernetes.sh | grep "kubeadm join"
  register: kubeadm_join_command

- name: set join command as fact
  set_fact: joincommand="{{kubeadm_join_command.stdout}}"

