---
- name: Login As Super User
  command: "oc login -u {{ admin_user }} -p {{ admin_password }}"
  when: cluster=="openshift"
        and admin_user is defined
        and admin_password is defined

- set_fact:
    heketi_route: unused

- name: Render storage-cns deployment yaml
  template:
    src: storage-cns.yml
    dest: /tmp/storage-cns.yml

- name: Delete storage-cns Resources
  command: kubectl delete -f /tmp/storage-cns.yml --ignore-not-found
