---
galaxy_info:
  author: Kubevirt Development <kubevirt-dev <kubevirt-dev@googlegroups.com>>
  description: Deploy Kubevirt Web UI
  company: Red Hat, Inc.
  license: Apache License, Version 2.0
  min_ansible_version: 2.4
  platforms:
  - name: EL
    versions:
    - 7
  - name: Fedora
    versions:
    - all
  categories:
  - openshift
