- hosts: masters[0]
  connection: local
  gather_facts: False
  # unset http_proxy. required for running in the CI
  environment:
    http_proxy: ""
  vars:
    admin_username: "test_admin"
    admin_password: "123456"
    master_fqdn: "{{ hostvars[groups['masters'][0]]['ansible_fqdn'] }}"
  roles:
    - role: cluster-login
