---
- hosts: masters[0]
  vars:
    storage_role: storage-demo
  # unset http_proxy. required for running in the CI
  environment:
    http_proxy: ""
  roles:
    - role: "{{ storage_role }}"
    - role: "cdi"

- hosts: masters nodes
  vars:
    storage_role: storage-demo
  gather_facts: False
  # unset http_proxy. required for running in the CI
  environment:
    http_proxy: ""
  roles:
    - role: storage-demo-nodeconfig
      when: storage_role == 'storage-demo'

- hosts: localhost
  vars:
  gather_facts: False
  # unset http_proxy. required for running in the CI
  environment:
    http_proxy: ""
  roles:
    - roles: storage-cinder
  when: storage_role == 'storage-cinder'
