---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ sriovcni_provisioner_name }}
  namespace: {{ namespace }}
  labels:
    tier: node
    app: sriov-cni
spec:
  template:
    metadata:
      labels:
        tier: node
        app: sriov-cni
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: kube-sriov-cni
        image: {{ sriovcni_provisioner_repo }}:{{ sriovcni_provisioner_release }}
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        volumeMounts:
        - name: cnibin
          mountPath: /host/opt/cni/bin
      volumes:
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
